### PR TITLE
Disable proxy server tests since not required any more

### PR DESCRIPTION
**Pull request by t-mon**

### CODE REVIEW

**Comment by mzanetti** [comment]
Perhaps remove the entire ols proxy code completely? There's absolutely no chance we'll be going back to AWS in that way... And even if, it's still in the history.

**Comment by t-mon** [comment]
> 

yeah...thought I still keep it a bit running for older instances coming online...next relase I'd suggest

**Comment by mzanetti** [comment]
the app won't connect via the old proxy any more either... no need to keep this

**Review by mzanetti — CHANGES_REQUESTED** [review]
please also remove the files

**Comment by t-mon** [comment]
Deprecated, see #36

**Pull request closed without merging**
